/**
 * Generate the Office add-in manifest.
 *
 * The manifest is not a static file in the repository because almost every
 * value in it is a URL that has to match wherever the build is deployed. It is
 * generated into `dist/` alongside the pages it points at, so the manifest and
 * the task pane it loads can never disagree about where they live.
 *
 * `<Version>` comes from the release tag by way of `tools/version/resolve.ts`.
 * Office requires four numeric components, so a tag of `v1.2.3` becomes
 * `1.2.3.0` — the fourth is always zero. See that module for why.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { generateIcons } from "../icons/generate.js";
import { prereleaseWarning, resolveVersion } from "../version/resolve.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const DIST = join(ROOT, "apps", "web", "dist");

/**
 * Stable identity of the add-in. Office keys installed add-ins on this, so it
 * must never change for a given add-in — a new GUID reads as a new product.
 */
const ADDIN_ID = "8a867a30-22b0-4de5-ba22-39c124b74dfa";

export interface ManifestOptions {
  /** Absolute base URL the add-in is served from, with a trailing slash. */
  readonly baseUrl: string;
  readonly version: string;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function renderManifest({ baseUrl, version }: ManifestOptions): string {
  const url = (path: string) => escapeXml(new URL(path, baseUrl).toString());
  const origin = escapeXml(new URL(baseUrl).origin);

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ReCite for Microsoft Word.

  Generated by tools/manifest/generate.ts — do not edit by hand; edit the
  generator, and rebuild. The version comes from the release tag.

  To install: Word > Home > Add-ins > More Add-ins > My Add-ins >
  Upload My Add-in, and choose this file.
-->
<OfficeApp
  xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
  xsi:type="TaskPaneApp">

  <Id>${ADDIN_ID}</Id>
  <Version>${escapeXml(version)}</Version>
  <ProviderName>ReCite contributors</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="ReCite" />
  <Description DefaultValue="Check case law citations in the open document: impossible reporter and year pairings, non-precedential authority, inconsistent abbreviations, and citations missing from your authority list. Runs locally; document text is not uploaded." />
  <IconUrl DefaultValue="${url("icons/icon-32.png")}" />
  <HighResolutionIconUrl DefaultValue="${url("icons/icon-80.png")}" />
  <SupportUrl DefaultValue="${url("")}" />

  <AppDomains>
    <AppDomain>${origin}</AppDomain>
  </AppDomains>

  <Hosts>
    <Host Name="Document" />
  </Hosts>

  <Requirements>
    <Sets DefaultMinVersion="1.3">
      <Set Name="WordApi" MinVersion="1.3" />
    </Sets>
  </Requirements>

  <DefaultSettings>
    <SourceLocation DefaultValue="${url("taskpane.html")}" />
  </DefaultSettings>

  <!-- The add-in reads the document to find citations and writes back the
       corrections the user accepts, so it needs read/write. -->
  <Permissions>ReadWriteDocument</Permissions>

  <VersionOverrides
    xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
    xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Document">
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title" />
            <Description resid="GetStarted.Description" />
            <LearnMoreUrl resid="Url.Home" />
          </GetStarted>

          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="ReCite.Group">
                <Label resid="Group.Label" />
                <Icon>
                  <bt:Image size="16" resid="Icon.16" />
                  <bt:Image size="32" resid="Icon.32" />
                  <bt:Image size="80" resid="Icon.80" />
                </Icon>
                <Control xsi:type="Button" id="ReCite.OpenPane">
                  <Label resid="Button.Label" />
                  <Supertip>
                    <Title resid="Button.Label" />
                    <Description resid="Button.Tooltip" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16" />
                    <bt:Image size="32" resid="Icon.32" />
                    <bt:Image size="80" resid="Icon.80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ReCite.Taskpane</TaskpaneId>
                    <SourceLocation resid="Url.Taskpane" />
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>

    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16" DefaultValue="${url("icons/icon-16.png")}" />
        <bt:Image id="Icon.32" DefaultValue="${url("icons/icon-32.png")}" />
        <bt:Image id="Icon.80" DefaultValue="${url("icons/icon-80.png")}" />
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Url.Taskpane" DefaultValue="${url("taskpane.html")}" />
        <bt:Url id="Url.Home" DefaultValue="${url("")}" />
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GetStarted.Title" DefaultValue="ReCite is ready" />
        <bt:String id="Group.Label" DefaultValue="Citations" />
        <bt:String id="Button.Label" DefaultValue="Check citations" />
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="Choose Check citations on the Home tab to review the citations in this document." />
        <bt:String id="Button.Tooltip" DefaultValue="Find citation problems in this document and apply the corrections you accept." />
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
`;
}

/**
 * Where the add-in will be served from.
 *
 * Office requires absolute HTTPS URLs — it will not load a manifest with
 * relative paths — so the deployment origin has to be known at build time.
 * Derived from the GitHub Actions environment when running in CI, and
 * overridable with `RECITE_BASE_URL` for a fork or a custom domain.
 */
export function resolveBaseUrl(): string {
  const explicit = process.env.RECITE_BASE_URL;
  if (explicit) return explicit.endsWith("/") ? explicit : `${explicit}/`;

  const repository = process.env.GITHUB_REPOSITORY;
  if (repository) {
    const [owner, repo] = repository.split("/");
    if (owner && repo) return `https://${owner.toLowerCase()}.github.io/${repo}/`;
  }

  return "https://wbarnha.github.io/ReCite/";
}

function main(): void {
  const release = resolveVersion();
  const warning = prereleaseWarning(release);

  const baseUrl = resolveBaseUrl();

  generateIcons(join(DIST, "icons"));

  mkdirSync(DIST, { recursive: true });
  const path = join(DIST, "manifest.xml");
  writeFileSync(path, renderManifest({ baseUrl, version: release.product }), "utf8");

  console.log(`Wrote ${path}`);
  console.log(`  version:  ${release.product}  (${release.source})`);
  console.log(`  base URL: ${baseUrl}`);
  if (warning) {
    console.warn(`\nwarning: ${warning}`);
    if (process.env.GITHUB_ACTIONS) console.warn(`::warning::${warning}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
